## Pytorch Introduction

- PyTorch is a Python based scientific computation library providing two high-level features :
 <br><br>   - Tensor computing (like NumPy) with strong acceleration via graphics processing units (GPU). According to https://pytorch.org/docs/stable/torch.html, the torch package contains data structures for multi-dimensional tensors and defines mathematical operations over these tensors. Additionally, it provides many utilities for efficient serializing of Tensors and arbitrary types, and other useful utilities.
<br><br>    - Deep neural networks built on a type-based automatic differentiation system (PyTorch is an optimized tensor library for deep learning using GPUs and CPUs).
<br><br>   
- Major released dates - Facebook's AI Research lab (FAIR) 
    - PyTorch 1.0 - October 2, 2018
    - PyTorch 1.10 - October 21, 2021
<br><br>  
- PyTorch : Python API (https://pytorch.org/docs/stable/index.html)
     - torch
     - torch.nn
     - torch.nn.functional
     - torch.Tensor
     - Tensor Attributes
     - Tensor Views
     - torch.autograd
     - torch.cuda
     - torch.cuda.amp
     - etc.

  


In [1]:
import torch
torch.__version__

'1.10.0+cu102'

In [2]:
torch.get_num_threads()

8

## Pytorch tensors

- A torch tensor is a multi-dimensional matrix (array) containing elements of a single data type. Most PyTorch functionalities or features are built on tensors and tensor functions.
<br><br>
- A tensor can be 0 (scalar), 1 (vector), 2 (matrix), ..., or n dimensional.
<br><br>
- A tensor can be of any of the following supported data types:
    - torch.float32 or torch.float
    - torch.float64 or torch.double
    - torch.float16 or torch.half
    - torch.complex32
    - torch.complex64
    - torch.complex128 or torch.cdouble
    - torch.uint8
    - torch.int8
    - torch.int32 or torch.int
    - torch.int64 or torch.long
    - torch.bool
    - torch.quint8
    - etc.
    

In [3]:
# A simple example of creating 1D tensor
a = torch.ones (5, dtype=torch.uint8)
torch.is_tensor(a), a.shape, a.dtype

(True, torch.Size([5]), torch.uint8)

In [4]:
a

tensor([1, 1, 1, 1, 1], dtype=torch.uint8)

In [5]:
# A simple example of creating 2D tensor
b = torch.ones (3, 5)
torch.is_tensor(b), b.shape, b.dtype

(True, torch.Size([3, 5]), torch.float32)

In [6]:
b

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [7]:
# Generate tensor using the standard normal distribution
x = torch.randn(3,5)
x

tensor([[-0.6720, -1.0822,  2.2452, -0.4180,  0.8905],
        [-0.4218, -2.1663, -0.6457,  0.1963, -1.0655],
        [ 0.2046,  1.6135, -0.2824, -0.8712,  0.4065]])

In [8]:
# Simple tensor arithmetic operators
2.0 * x
x + b
x / b

tensor([[-0.6720, -1.0822,  2.2452, -0.4180,  0.8905],
        [-0.4218, -2.1663, -0.6457,  0.1963, -1.0655],
        [ 0.2046,  1.6135, -0.2824, -0.8712,  0.4065]])

In [9]:
# Simple demo of Broadcasting semantics - the following works
y = torch.ones (5,3)
z = torch.ones(3)
y, z, y+z

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([1., 1., 1.]),
 tensor([[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]]))

In [10]:
# Simple demo of Broadcasting semantics
y = torch.ones (3,5)
z = torch.ones(3)
y, z

(tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]),
 tensor([1., 1., 1.]))

In [11]:
# Simple demo of Broadcasting semantics - the following doesn't work
y + z

RuntimeError: The size of tensor a (5) must match the size of tensor b (3) at non-singleton dimension 1

In [12]:
# Simple demo of Broadcasting semantics - a fix of the last cell
y, z.unsqueeze(-1) # add one dimension to z after the last dim in z

(tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]),
 tensor([[1.],
         [1.],
         [1.]]))

In [13]:
# Simple demo of Broadcasting semantics 
y + z.unsqueeze(-1)

tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])

In [14]:
# Simple tensor reduction functions
x = torch.randint(10,(3,5))
x

tensor([[5, 8, 8, 4, 2],
        [0, 9, 3, 8, 7],
        [2, 5, 8, 0, 5]])

In [15]:
x.sum()        # full reduction, a tensor of dimension 0 is retured
x.sum(dim = 1) # reduction along dimension 1 axis (i.e, column-wise reduction), 
               # a tensor of dimension 1 is retured

tensor([27, 27, 20])

In [16]:
# Same results as those of last cell
torch.sum(x)   # full reduction, a tensor of dimension 0 is retured
torch.sum(x,1) # reduction along dimension 1 axis (i.e, column-wise reduction), 
               # a tensor of dimension 1 is retured

tensor([27, 27, 20])

### A matrix row (or column) normalization problem
<br>
- Given a 2D tensor (i.e., matrix), normalize all the rows (or columns) in the matrix 

In [17]:
x = torch.tensor([[1,2, 3],[4,5,6],[7,8, 9]])
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
# Normalize all row in x - step 1
x1 = x.sum(dim=1)
x1

tensor([ 6, 15, 24])

In [19]:
# Normalize all row in x - step 2
x2 = x1.unsqueeze(1) # add one more dimension at 1-th dimension
x2.shape, x, x2

(torch.Size([3, 1]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([[ 6],
         [15],
         [24]]))

In [20]:
# Normalize all row in x - step 3
x / x2

tensor([[0.1667, 0.3333, 0.5000],
        [0.2667, 0.3333, 0.4000],
        [0.2917, 0.3333, 0.3750]])

In [21]:
# Normalize all row in x - in one step
x / x.sum(1).unsqueeze(-1)       # -1 means to add one dimension after the last dimension

tensor([[0.1667, 0.3333, 0.5000],
        [0.2667, 0.3333, 0.4000],
        [0.2917, 0.3333, 0.3750]])

In [22]:
# Normalize all columns in x
x/x.sum(0)

tensor([[0.0833, 0.1333, 0.1667],
        [0.3333, 0.3333, 0.3333],
        [0.5833, 0.5333, 0.5000]])

## CUDA SEMANTICS
- https://pytorch.org/docs/stable/notes/cuda.html

torch.cuda is used to set up and run CUDA operations. It keeps track of the currently selected GPU, and all CUDA tensors you allocate will by default be created on that device. The selected device can be changed with a torch.cuda.device context manager.

However, once a tensor is allocated, you can do operations on it irrespective of the selected device, and the results will be always placed in on the same device as the tensor.

Cross-GPU operations are not allowed by default, with the exception of copy_() and other methods with copy-like functionality such as to() and cuda(). Unless you enable peer-to-peer memory access, any attempts to launch ops on tensors spread across different devices will raise an error.

In [2]:
cuda = torch.device('cuda')     # Default CUDA device
cuda0 = torch.device('cuda:0')
cuda2 = torch.device('cuda:2')  # GPU 2 (these are 0-indexed)

In [3]:
x = torch.tensor([1., 2.], device=cuda0)
# x.device is device(type='cuda', index=0)
y = torch.tensor([1., 2.]).cuda()
# y.device is device(type='cuda', index=0)

In [4]:
x, y

(tensor([1., 2.], device='cuda:0'), tensor([1., 2.], device='cuda:0'))

In [5]:
with torch.cuda.device(0):
    # allocates a tensor on GPU 0
    a = torch.tensor([[1., 1.],[1.,1.]], device=cuda)

    # transfers a tensor from CPU to GPU 0
    b = torch.randn(2,2).cuda()

    # You can also use ``Tensor.to`` to transfer a tensor:
    b2 = torch.randn(2,2).to(device=cuda)
    
    # matrix multiplication
    c = a @ b

In [6]:
a, b, c

(tensor([[1., 1.],
         [1., 1.]], device='cuda:0'),
 tensor([[-0.3435,  1.3492],
         [ 0.0152, -0.9463]], device='cuda:0'),
 tensor([[-0.3283,  0.4029],
         [-0.3283,  0.4029]], device='cuda:0'))