## Torch Math Operations
Functions for manipulating the content of the tensor through computaton

- Pointwise ops—Functions for obtaining a new tensor by applying a function to
each element independently, like abs and cos
- Reduction ops—Functions for computing aggregate values by iterating
through tensors, like mean, std, and norm
- Comparison ops—Functions for evaluating numerical predicates over tensors,
like equal and max
- Spectral ops—Functions for transforming in and operating in the frequency
domain, like stft and hamming_window
- Other operations—Special functions operating on vectors, like cross, or matrices,
like trace
- BLAS and LAPACK operations—Functions following the Basic Linear Algebra
Subprograms (BLAS) specification for scalar, vector-vector, matrix-vector,
and matrix-matrix operations

In [1]:
import torch
torch.__version__

'1.8.0+cu111'

In [2]:
a = torch.randn(3,5) # 2D matrix
a

tensor([[-2.0029, -0.6807, -0.3223, -0.9472,  0.6192],
        [-0.7948, -0.8724, -0.8689, -1.3111,  0.6606],
        [ 0.2405,  1.9422, -0.4261,  0.4261, -1.0424]])

In [3]:
# Compute softmax of eeach row of a
a_softmax = a.exp()/a.exp().sum(1).unsqueeze(1)
a_softmax

tensor([[0.0374, 0.1402, 0.2006, 0.1074, 0.5144],
        [0.1293, 0.1196, 0.1200, 0.0771, 0.5540],
        [0.1180, 0.6468, 0.0606, 0.1420, 0.0327]])

In [4]:
a_softmax.sum(1).unsqueeze(1)

tensor([[1.0000],
        [1.0000],
        [1.0000]])

In [5]:
# Reduction function : argmax Returns the indices of the maximum value of 
# all elements in the input tensor.
a_softmax.argmax(1).unsqueeze(1)


tensor([[4],
        [4],
        [1]])

## BLAS and LAPACK operations

https://pytorch.org/docs/stable/torch.html 

- code>addmv</code>

Performs a matrix-vector product of the matrix mat and the vector vec.

- <code>addr</code>

Performs the outer-product of vectors vec1 and vec2 and adds it to the matrix input.

- <code>baddbmm</code>

Performs a batch matrix-matrix product of matrices in batch1 and batch2.

- <code>bmm</code>

Performs a batch matrix-matrix product of matrices stored in input and mat2.

- <code>chain_matmul</code>

Returns the matrix product of the NN 2-D tensors.

- <code>cholesky</code>

Computes the Cholesky decomposition of a symmetric positive-definite matrix AA or for batches of symmetric positive-definite matrices.

- <code>cholesky_inverse</code>

Computes the inverse of a symmetric positive-definite matrix AA using its Cholesky factor uu: returns matrix inv.

- <code>cholesky_solve</code>

Solves a linear system of equations with a positive semidefinite matrix to be inverted given its Cholesky factor matrix uu.

- <code>dot</code>

Computes the dot product of two 1D tensors.

- <code>eig</code>

Computes the eigenvalues and eigenvectors of a real square matrix.

- <code>geqrf</code>

This is a low-level function for calling LAPACK’s geqrf directly.

- <code>ger</code>

Alias of torch.outer().

- <code>inner</code>

Computes the dot product for 1D tensors.

- <code>inverse</code>

Alias for torch.linalg.inv()

- <code>det</code>

Alias for torch.linalg.det()

- <code>logdet</code>

Calculates log determinant of a square matrix or batches of square matrices.

- <code>slogdet</code>

Alias for torch.linalg.slogdet()

- <code>lstsq</code>

Computes the solution to the least squares and least norm problems for a full rank matrix AA of size (m \times n)(m×n) and a matrix BB of size (m \times k)(m×k).

- <code>lu</code>

Computes the LU factorization of a matrix or batches of matrices A.

- <code>lu_solve</code>

Returns the LU solve of the linear system Ax = bAx=b using the partially pivoted LU factorization of A from torch.lu().

- <code>lu_unpack</code>

Unpacks the data and pivots from a LU factorization of a tensor into tensors L and U and a permutation tensor P such that LU_data, LU_pivots = (P @ L @ U).lu().

- <code>matmul</code>

Matrix product of two tensors.

- <code>atrix_power</code>

Alias for torch.linalg.matrix_power()

- <code>matrix_rank</code>

Returns the numerical rank of a 2-D tensor.

- <code>matrix_exp</code>

Computes the matrix exponential of a square matrix or of each square matrix in a batch.

- <code>mm</code>

Performs a matrix multiplication of the matrices input and mat2.

- <code>mv</code>

Performs a matrix-vector product of the matrix input and the vector vec.

- <code>orgqr</code>

Alias for torch.linalg.householder_product().

- <code>ormqr</code>

Computes the matrix-matrix multiplication of a product of Householder matrices with a general matrix.

- <code>outer</code>

Outer product of input and vec2.

- <code>pinverse</code>

Alias for torch.linalg.pinv()

- <code>qr</code>

Computes the QR decomposition of a matrix or a batch of matrices input, and returns a namedtuple (Q, R) of tensors such that \text{input} = Q Rinput=QR with QQ being an orthogonal matrix or batch of orthogonal matrices and RR being an upper triangular matrix or batch of upper triangular matrices.

- <code>solve</code>

This function returns the solution to the system of linear equations represented by AX = BAX=B and the LU factorization of A, in order as a namedtuple solution, LU.

- <code>svd</code>

Computes the singular value decomposition of either a matrix or batch of matrices input.

- <code>svd_lowrank</code>

Return the singular value decomposition (U, S, V) of a matrix, batches of matrices, or a sparse matrix AA such that A \approx U diag(S) V^TA≈Udiag(S)V 
T
 .

- <code>pca_lowrank</code>

Performs linear Principal Component Analysis (PCA) on a low-rank matrix, batches of such matrices, or sparse matrix.

- <code>symeig</code>

This function returns eigenvalues and eigenvectors of a real symmetric or complex Hermitian matrix input or a batch thereof, represented by a namedtuple (eigenvalues, eigenvectors).

- <code>lobpcg</code>

Find the k largest (or smallest) eigenvalues and the corresponding eigenvectors of a symmetric positive defined generalized eigenvalue problem using matrix-free LOBPCG methods.

- <code>trapz</code>

Alias for torch.trapezoid().

- <code>trapezoid</code>

Computes the trapezoidal rule along dim.

- <code>cumulative_trapezoid</code>

Cumulatively computes the trapezoidal rule along dim.

- <code>triangular_solve</code>

Solves a system of equations with a triangular coefficient matrix AA and multiple right-hand sides bb.

- <code>vdot</code>

Computes the dot product of two 1D tensors.

In [6]:
a = torch.ones(6400, 6400, dtype = torch.float32)
b = torch.ones(6400, 6400, dtype = torch.float32)

In [7]:
%%time
c = torch.matmul(a,b)

Wall time: 1.12 s


In [9]:
a_cuda = a.to(device='cuda')
b_cuda = b.to(device='cuda')

In [10]:
a_cuda.device, b_cuda.device

(device(type='cuda', index=0), device(type='cuda', index=0))

In [11]:
%%time
c_cuda = torch.matmul(a_cuda, b_cuda)

Wall time: 602 ms


In [12]:
c_cuda.shape, c_cuda.dtype, c_cuda.device

(torch.Size([6400, 6400]), torch.float32, device(type='cuda', index=0))

In [14]:
c_cuda[0,0].item()

6400.0