**Example: Multiplication of two matrices by each other of size 3×3.**


    matrix1 = [[12, 7, 3],
               [4,  5, 6],
               [7,  8, 9]]
                 
    matrix2 = [[5, 8, 1],
               [6, 7, 3],
               [4, 5, 9]]

    matrix1 @ matrix2 =[[114, 160, 60]
                        [74,   97, 73]
                        [119, 157, 112]]

Methods to multiply two matrices in python
1. Using explicit for loops: This is a simple technique to multiply matrices but one of the expensive method for larger input data set. In this, we use nested for loops to iterate each row and each column.
If matrix1 is a n x k matrix and matrix2 is a k x m matrix, the result is an n x m matrix.
2. Using Numpy : Multiplication using Numpy also know as vectorization which main aim to reduce or remove the explicit use of for loops in the program by which computation becomes faster.
Numpy is a build in a package in python for array-processing and manipulation.For larger matrix operations we use numpy python package which is 1000 times faster than iterative one method.


In [6]:
# input two matrices of size n x m
matrix1 = [[12,7,3],
        [4 ,5,6],
        [7 ,8,9]]
matrix2 = [[5,8,1],
        [6,7,3],
        [4,5,9]]
res = [[0 for x in range(3)] for y in range(3)] 

# explicit for loops
for i in range(len(matrix1)):
    for j in range(len(matrix2[0])):
        for k in range(len(matrix2)):
            # resulted matrix
            res[i][j] += matrix1[i][k] * matrix2[k][j]
  
print (res)

[[114, 160, 60], [74, 97, 73], [119, 157, 112]]


In the following example we will use dot product and in mathematics the dot product is an algebraic operation that takes two vectors of equal size and returns a single number. The result is calculated by multiplying corresponding entries and adding up those products.

In [1]:
import numpy as np
  
# input two matrices
mat1 = [[12, 7, 3],[4 ,5, 6],[7, 8, 9]] # List,  not np.ndarray
mat2 = ([5, 8, 1],[6, 7, 3],[4, 5, 9])  # Tuple, not np.ndarray
  
# This will return dot product of two matrices
res = np.dot(mat1, mat2) # by doing (row-vector) dot (column-vector); 
                         # works on array-like data structures
  
# print resulted matrix
print(res)
type(res)

[[114 160  60]
 [ 74  97  73]
 [119 157 112]]


numpy.ndarray

In [2]:
# same result will be obtained when we use @ operator 
# as shown below(only in python >3.5)
import numpy as np
  
# Convert list and Tuple to two np.ndarrays
mat1 = np.asarray([[12, 7, 3],[4 ,5, 6],[7, 8, 9]])
mat2 = np.asarray(([5, 8, 1],[6, 7, 3],[4, 5, 9]))

# This will return matrix product of two array
res = mat1 @ mat2
  
# print resulted matrix
print(res)

[[114 160  60]
 [ 74  97  73]
 [119 157 112]]


In [3]:
# Same as res = mat1 @ mat2
res = mat1.dot(mat2)
  
# print resulted matrix
print(res)

[[114 160  60]
 [ 74  97  73]
 [119 157 112]]


In [16]:
row, k, col = 3200, 3200, 3200

# Create a list containing row lists, each of k items, all set to 1.0
matrix1 = [[1.0 for x in range(k)] for y in range(row)]
# Create a list containing k lists, each of col items, all set to 1.0
matrix2 = [[1.0 for x in range(col)] for y in range(k)]

res = [[0 for x in range(col)] for y in range(row)] 

In [17]:
# Timing of multiplication of two matrices of size row x k and k x col
# Be warned; this may take about 2 hours to complete for 3200x3200 matrices.
%%time
# explicit for loops
for i in range(len(matrix1)):
    for j in range(len(matrix2[0])):
        for k in range(len(matrix2)):
            # resulted matrix
            res[i][j] += matrix1[i][k] * matrix2[k][j]
print(f"number of rows = {len(res)}"), print(f"number of cols = {len(res[0])}")
print(f"res[0][0] = {res[0][0]}")

number of rows = 3200
number of cols = 3200
res[0][0] = 3200.0
Wall time: 1h 59min 46s


In [4]:
# same result will be obtained when we use @ operator 
# as shown below(only in python >3.5)
import numpy as np

s = 3200
# input two matrices
#mat1 = np.ones((s,s), dtype="float32")
#mat2 = np.ones((s,s), dtype="float32")

mat1 = np.random.random((s, s))
mat2 = np.random.random((s, s))

print(len(mat1))
print(len(mat2))
print(mat1.shape)

3200
3200
(3200, 3200)


In [5]:
%%time 
res = np.matmul(mat1,mat2) # mat1 @ mat2
print(res.ndim), print(res.shape)
print(res[0,0])

2
(3200, 3200)
808.2164223308997
Wall time: 239 ms
